{"text": "2023-03-29T13:06:34.313383+0300 ERROR An error has been caught in function 'notify', process 'MainProcess' (9608), thread 'MainThread' (10456):\nTraceback (most recent call last):\n\n  File \"C:\\Program Files\\JetBrains\\PyCharm Community Edition 2021.2.3\\plugins\\python-ce\\helpers\\pydev\\pydevd.py\", line 2173, in <module>\n    main()\n    └ <function main at 0x0000021794ED17E0>\n\n  File \"C:\\Program Files\\JetBrains\\PyCharm Community Edition 2021.2.3\\plugins\\python-ce\\helpers\\pydev\\pydevd.py\", line 2164, in main\n    globals = debugger.run(setup['file'], None, None, is_module)\n              │        │   │                          └ False\n              │        │   └ {'port': 63809, 'vm_type': None, 'client': '127.0.0.1', 'server': False, 'DEBUG_RECORD_SOCKET_READS': False, 'multiproc': Tru...\n              │        └ <function PyDB.run at 0x0000021794ED0820>\n              └ <__main__.PyDB object at 0x0000021794D42D70>\n\n  File \"C:\\Program Files\\JetBrains\\PyCharm Community Edition 2021.2.3\\plugins\\python-ce\\helpers\\pydev\\pydevd.py\", line 1476, in run\n    return self._exec(is_module, entry_point_fn, module_name, file, globals, locals)\n           │    │     │          │               │            │     │        └ {'__name__': '__main__', '__doc__': None, '__package__': '', '__loader__': <_frozen_importlib_external.SourceFileLoader objec...\n           │    │     │          │               │            │     └ {'__name__': '__main__', '__doc__': None, '__package__': '', '__loader__': <_frozen_importlib_external.SourceFileLoader objec...\n           │    │     │          │               │            └ 'C:/Users/mi/PycharmProjects/Botkits/exchange_bot/app.py'\n           │    │     │          │               └ None\n           │    │     │          └ ''\n           │    │     └ False\n           │    └ <function PyDB._exec at 0x0000021794ED08B0>\n           └ <__main__.PyDB object at 0x0000021794D42D70>\n\n  File \"C:\\Program Files\\JetBrains\\PyCharm Community Edition 2021.2.3\\plugins\\python-ce\\helpers\\pydev\\pydevd.py\", line 1483, in _exec\n    pydev_imports.execfile(file, globals, locals)  # execute the script\n    │             │        │     │        └ {'__name__': '__main__', '__doc__': None, '__package__': '', '__loader__': <_frozen_importlib_external.SourceFileLoader objec...\n    │             │        │     └ {'__name__': '__main__', '__doc__': None, '__package__': '', '__loader__': <_frozen_importlib_external.SourceFileLoader objec...\n    │             │        └ 'C:/Users/mi/PycharmProjects/Botkits/exchange_bot/app.py'\n    │             └ <function execfile at 0x00000217941C25F0>\n    └ <module '_pydev_bundle.pydev_imports' from 'C:\\\\Program Files\\\\JetBrains\\\\PyCharm Community Edition 2021.2.3\\\\plugins\\\\python...\n\n  File \"C:\\Program Files\\JetBrains\\PyCharm Community Edition 2021.2.3\\plugins\\python-ce\\helpers\\pydev\\_pydev_imps\\_pydev_execfile.py\", line 18, in execfile\n    exec(compile(contents+\"\\n\", file, 'exec'), glob, loc)\n                 │              │              │     └ {'__name__': '__main__', '__doc__': None, '__package__': '', '__loader__': <_frozen_importlib_external.SourceFileLoader objec...\n                 │              │              └ {'__name__': '__main__', '__doc__': None, '__package__': '', '__loader__': <_frozen_importlib_external.SourceFileLoader objec...\n                 │              └ 'C:/Users/mi/PycharmProjects/Botkits/exchange_bot/app.py'\n                 └ \"import logging\\nfrom utils.set_bot_commands import set_default_commands\\nlogging.basicConfig(level=logging.INFO)\\n\\n\\n\\nasyn...\n\n  File \"C:/Users/mi/PycharmProjects/Botkits/exchange_bot/app.py\", line 15, in <module>\n    executor.start_polling(dp, skip_updates=False, on_startup=on_startup)\n    │        │             │                                  └ <function on_startup at 0x0000021794F52CB0>\n    │        │             └ <aiogram.dispatcher.dispatcher.Dispatcher object at 0x0000021797D15690>\n    │        └ <function start_polling at 0x0000021795A6A0E0>\n    └ <module 'aiogram.utils.executor' from 'C:\\\\Users\\\\mi\\\\PycharmProjects\\\\Botkits\\\\exchange_bot\\\\venv\\\\lib\\\\site-packages\\\\aiogr...\n\n  File \"C:\\Users\\mi\\PycharmProjects\\Botkits\\exchange_bot\\venv\\lib\\site-packages\\aiogram\\utils\\executor.py\", line 45, in start_polling\n    executor.start_polling(\n    │        └ <function Executor.start_polling at 0x0000021795A6AB00>\n    └ <aiogram.utils.executor.Executor object at 0x0000021794D7AB90>\n\n  File \"C:\\Users\\mi\\PycharmProjects\\Botkits\\exchange_bot\\venv\\lib\\site-packages\\aiogram\\utils\\executor.py\", line 323, in start_polling\n    loop.run_forever()\n    │    └ <function ProactorEventLoop.run_forever at 0x0000021794EBCE50>\n    └ <ProactorEventLoop running=True closed=False debug=False>\n\n  File \"C:\\Users\\mi\\AppData\\Local\\Programs\\Python\\Python310\\lib\\asyncio\\windows_events.py\", line 321, in run_forever\n    super().run_forever()\n\n  File \"C:\\Users\\mi\\AppData\\Local\\Programs\\Python\\Python310\\lib\\asyncio\\base_events.py\", line 595, in run_forever\n    self._run_once()\n    │    └ <function BaseEventLoop._run_once at 0x0000021794E67F40>\n    └ <ProactorEventLoop running=True closed=False debug=False>\n\n  File \"C:\\Users\\mi\\AppData\\Local\\Programs\\Python\\Python310\\lib\\asyncio\\base_events.py\", line 1881, in _run_once\n    handle._run()\n    │      └ <function Handle._run at 0x0000021794E2F910>\n    └ <Handle <TaskStepMethWrapper object at 0x00000217A70B55D0>()>\n\n  File \"C:\\Users\\mi\\AppData\\Local\\Programs\\Python\\Python310\\lib\\asyncio\\events.py\", line 80, in _run\n    self._context.run(self._callback, *self._args)\n    │    │            │    │           │    └ <member '_args' of 'Handle' objects>\n    │    │            │    │           └ <Handle <TaskStepMethWrapper object at 0x00000217A70B55D0>()>\n    │    │            │    └ <member '_callback' of 'Handle' objects>\n    │    │            └ <Handle <TaskStepMethWrapper object at 0x00000217A70B55D0>()>\n    │    └ <member '_context' of 'Handle' objects>\n    └ <Handle <TaskStepMethWrapper object at 0x00000217A70B55D0>()>\n\n  File \"C:\\Users\\mi\\PycharmProjects\\Botkits\\exchange_bot\\venv\\lib\\site-packages\\aiogram\\dispatcher\\handler.py\", line 117, in notify\n    response = await handler_obj.handler(*args, **partial_data)\n                     │           │        │       └ {}\n                     │           │        └ (<Update {\"update_id\": 926788394, \"message\": {\"message_id\": 3710, \"from\": {\"id\": 381252111, \"is_bot\": false, \"first_name\": \"В...\n                     │           └ <bound method Dispatcher.process_update of <aiogram.dispatcher.dispatcher.Dispatcher object at 0x0000021797D15690>>\n                     └ Handler.HandlerObj(handler=<bound method Dispatcher.process_update of <aiogram.dispatcher.dispatcher.Dispatcher object at 0x0...\n\n  File \"C:\\Users\\mi\\PycharmProjects\\Botkits\\exchange_bot\\venv\\lib\\site-packages\\aiogram\\dispatcher\\dispatcher.py\", line 256, in process_update\n    return await self.message_handlers.notify(update.message)\n                 │    │                │      │      └ <aiogram.types.fields.Field object at 0x0000021795902F20>\n                 │    │                │      └ <Update {\"update_id\": 926788394, \"message\": {\"message_id\": 3710, \"from\": {\"id\": 381252111, \"is_bot\": false, \"first_name\": \"Вл...\n                 │    │                └ <function Handler.notify at 0x0000021795995120>\n                 │    └ <aiogram.dispatcher.handler.Handler object at 0x0000021797D157E0>\n                 └ <aiogram.dispatcher.dispatcher.Dispatcher object at 0x0000021797D15690>\n\n> File \"C:\\Users\\mi\\PycharmProjects\\Botkits\\exchange_bot\\venv\\lib\\site-packages\\aiogram\\dispatcher\\handler.py\", line 117, in notify\n    response = await handler_obj.handler(*args, **partial_data)\n                     │           │        │       └ {}\n                     │           │        └ (<Message {\"message_id\": 3710, \"from\": {\"id\": 381252111, \"is_bot\": false, \"first_name\": \"Влад\", \"username\": \"ulad_islau\", \"la...\n                     │           └ <function test at 0x0000021797CCECB0>\n                     └ Handler.HandlerObj(handler=<function test at 0x0000021797CCECB0>, spec=FullArgSpec(args=['message'], varargs=None, varkw=None...\n\n  File \"C:\\Users\\mi\\PycharmProjects\\Botkits\\exchange_bot\\handlers\\users\\start.py\", line 125, in test\n    a = 1/0\n\nZeroDivisionError: division by zero\n", "record": {"elapsed": {"repr": "0:00:04.814781", "seconds": 4.814781}, "exception": {"type": "ZeroDivisionError", "value": "division by zero", "traceback": true}, "extra": {}, "file": {"name": "handler.py", "path": "C:\\Users\\mi\\PycharmProjects\\Botkits\\exchange_bot\\venv\\lib\\site-packages\\aiogram\\dispatcher\\handler.py"}, "function": "notify", "level": {"icon": "❌", "name": "ERROR", "no": 40}, "line": 117, "message": "An error has been caught in function 'notify', process 'MainProcess' (9608), thread 'MainThread' (10456):", "module": "handler", "name": "aiogram.dispatcher.handler", "process": {"id": 9608, "name": "MainProcess"}, "thread": {"id": 10456, "name": "MainThread"}, "time": {"repr": "2023-03-29 13:06:34.313383+03:00", "timestamp": 1680084394.313383}}}
